seed: 42

data_cleaning:
  log_sales_filter:
    enabled: true
    keep_ranges:
      - max: 2
      - min: 6

  customers_filter:
    enabled: true
    max_customers: 7000

  sales_capping:
    enabled: true
    threshold: 40000
    replace_with: 0

tuning:
  method: RandomSearchCV
  cv: 3
  n_iter: 30

param_dist:
    model__learning_rate: [0.01, 0.03, 0.05, 0.1]
    model__max_depth: [5, 8, 12]
    model__min_child_weight: [1, 5, 10]
    model__subsample: [0.7, 0.8, 1.0]
    model__gamma: [0, 0.1, 0.5]
    model__reg_alpha: [0, 0.1, 1]
    model__reg_lambda: [1, 5, 10]